### ISSUE TITLE
Style guide doesn't include v3 commandments

### ISSUE THREAD

**Issue by utako** [cloudfoundry/cc-api-v3-style-guide#1]
This was in an email after a v3 meeting a few months ago. We should maybe go over their relevance now, but I'd definitely like to see mention of how we use fetchers (e.g. DropletListFetcher), actions (e.g. AppUpdate), and stub out controller tests. 

They are as follows:

• Fetchers return concrete things
• Fetcher returns array of concrete things
• Fetchers are specific to an operation
• Transactions are in actions by default
• There should be a message object responsible for basic validation on requests
• Controller tests should not touch the database
• During handler -> action transition, do not lose logic from access classes
• If your actions don't have loggers, you broke them

**Comment by zrob** [comment]
Yeah, an implementation style guide may be useful as a separate doc.  This style guide is sort of independent of the underlying implementation
