### ISSUE TITLE
Pagination order_direction and order_by is limiting.

### ISSUE THREAD

**Issue by zrob** [cloudfoundry/cc-api-v3-style-guide#10]
Imagine we want to order by two columns.  We could potentially say `?order_by=columnA,columnB`, but then how would we sort by each?  Maybe `?order_by=columnA,columnB&order_direction=asc,desc` and the requests have to line up in order. This seems awkward.

Perhaps a better solution is `?order_by=+columnA,-columnB`.  The `+` and `-` would correspond to ascending and descending.

**Comment by Gerg** [comment]
Dieu wants to do this. Les do it!

**Comment by osis** [comment]
+1

**Comment by jeffpak** [comment]
Done! Added a section in pagination that indicates how to do order direction. bf1daf6

:smile_cat:
