### ISSUE TITLE
Array query params feel awkward.

### ISSUE THREAD

**Issue by zrob** [cloudfoundry/cc-api-v3-style-guide#12]
Perhaps we could prefer `?space_guid=guidA,guidB,guidC` over `?space_guids[]=guidA&space_guids[]=guidB`.

**Comment by Gerg** [comment]
Conventions:

`?space_guid=guidA,guidB,guidC`
- JSON API

`?space_guids[]=guidA&space_guids[]=guidB`
- PHP
- HTTParty

`?space_guids[0]=guidA&space_guids[1]=guidB`
- Typhoeus

`?space_guid=guidA&space_guid=guidB`
- HTTP.rb
- Net::HTTP

**Comment by Gerg** [comment]
Via cage match:

The JSON API style was preferred because it was easier for human minds. Dieu is afraid of comma encoding.

**Comment by Gerg** [comment]
We are still onboard with the JSON API style lists.

**Comment by jeffpak** [comment]
Style guide already seems consistent with JSON API style lists, based on previous changes.
