### ISSUE TITLE
Field naming should be described

### ISSUE THREAD

**Issue by zrob** [cloudfoundry/cc-api-v3-style-guide#14]
We specify how query parameters must be named, we should do the same for fields on a resource.

**Comment by Gerg** [comment]
Maybe we should just make a 'naming' section that covers query parameters, field names, and examples. Make sure not to remove the square bracket thing. It is still used for the subsets of fields thing a la `fields[space]`.

Do what seems right (in a not vague way).

**Comment by jeffpak** [comment]
Added a standalone section called Field Names under Query Parameters, since it seems easier to navigate to rather than a combined 'Naming' section. 07c27255

:cactus:
