### ISSUE TITLE
"Overview/List of Terms" should include definitions

### ISSUE THREAD

**Issue by ships** [cloudfoundry/cc-api-v3-style-guide#15]
"Collection" is well defined, but it would be helpful to have a specification of what can constitute a resource (possibly more relevant to describe in terms of what cannot be a resource)

i.e. Resource: any CF component that can be reported by the CC

or similar

**Comment by Gerg** [comment]
Let's delete the glossary for now, it is not helpful. We should definitely have a glossary for the API docs.

**Comment by jeffpak** [comment]
Glossary deleted 06767c3

:zap:
