### ISSUE TITLE
Inconsistent use of verbs

### ISSUE THREAD

**Issue by ships** [cloudfoundry/cc-api-v3-style-guide#16]
There are a few places which use out-of-spec verbs. i.e. "Requests/URL Structure": "Collections of resources are referenced by" rather than "shall be referenced by/may be referenced by/etc". Choose relevant one for consistency and clarity

**Comment by Gerg** [comment]
Move to the not Greg version. The styleguide **SHALL** not include the words "shall."

The styleguide **SHALL** take a definitive stance on what we are doing. There **SHALL** not be any "mays" or "mights."

**Comment by jeffpak** [comment]
Done. Replaced "shall" and "should" to "must". Kept "may" in there since those don't seem replaceable. 4870539

:tada:
