### ISSUE TITLE
PUT to trigger updating events on a resource

### ISSUE THREAD

**Issue by ships** [cloudfoundry/cc-api-v3-style-guide#17]
We currently use PUT verb to /v3/apps/:guid/start (see [the api docs](http://apidocs.cloudfoundry.org/214/apps_%28experimental%29/starting_an_app.html)). However, it is here specified that POST is to "trigger action on a resource" whereas PUT to "request that an action is triggered". I'm not totally clear when we would ever be "triggering" rather than "requesting to trigger", so either:

a) we should remove the POST-as-trigger explanation, or
b) we should include an example of where POST is used to trigger, and another of where PUT is used to request triggering

**Comment by ships** [comment]
After reading the Actions section, at the very least i believe `Used to create a resource or trigger an action on a resource.` should be reworded under POST. The use of "action" here conflicts with the Action proper type, which demands PUT.

**Comment by Gerg** [comment]
Via cage match:  
PUT seems reasonable for actions, as long as it is the only use for PUT and well documented. PATCH should be the only way to update fields on resources. (In a parallel universe, POST /actions/start might also work)
- PATCH should never affect the runtime. Instead, actions.
