### ISSUE TITLE
BATCH operations on collections of resources that already exist

### ISSUE THREAD

**Issue by ships** [cloudfoundry/cc-api-v3-style-guide#18]
We have GET for collections via query parameters for filtering, etc
It could be nice to have functionality like PATCH or DELETE for collections, such as if I wanted to filter apps by associated current droplet and update all those apps' current droplet. To do this, we would need something like PATCH /v3/apps/current_droplet and allow query parameters to somehow filter the selected apps.

 note that This is a potentially somewhat complex operation, i'm not quite sure what the format for such a request would be.

**Comment by ships** [comment]
at the moment "PATCH requests **shall NOT** include query parameters"

**Comment by Gerg** [comment]
We are not going to worry about this for v3.
