### ISSUE TITLE
Style guide does not address caching scenarios

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry/cc-api-v3-style-guide#2]
Web UI's and internal Cloud Foundry services constantly query endpoints today looking for changes so they can update their state of the world. The performance of these applications could be improved if the API supported mechanisms such as ETag/If-None-Match or If-Modified-Since.

The new v3 guide should include a section on caching and the general patterns we expect clients to use.

**Comment by zrob** [comment]
+1

**Comment by Gerg** [comment]
This is definitely something we would like to include in the CC API. Since this in an additive change, we could easily include this in a 3.x+ release.

:+1:

**Comment by sweinstein22** [comment]
We are archiving this repo in favor of colocating the information [in the ccng repo](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/docs/v3_style_guide.md), any issues or PRs are welcome in its new location. Thanks!
