### ISSUE TITLE
Style guide does not include any fine grained select/query mechanisms

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry/cc-api-v3-style-guide#3]
The current v2 api supports [query operators](https://github.com/cloudfoundry/cloud_controller_ng/blob/b137f57cd29aceb397fa46dcf7192ba4eaff34c7/lib/vcap/rest_api/query.rb#L89).  These can be useful on collection endpoints to scope the query to a meaningful subset.

A similar concept should probably be present in the v3 api.

**Comment by zrob** [comment]
Yeah this is interesting.  I wonder if we should define this now or wait till we have a feature that forces it.

I also wonder whether the >, <, etc cases are good to generalize or if when we implement a feature we'd rather have a specific query param for the desired use case eg `?events_after=738`

**Comment by sykesm** [comment]
Whether or not you implement it, I think you should think about it how you would render it so there's some level of consistency across the endpoints.

**Comment by Gerg** [comment]
We will add some examples to the style guide for number/ date filtering.

**Comment by jeffpak** [comment]
Added an example of filtering query parameters to the filtering section. 34bc264
:dart:

**Comment by zrob** [comment]
We don't want to use the q= format, so we should still address this.

**Comment by sweinstein22** [comment]
We are archiving this repo in favor of colocating the information [in the ccng repo](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/docs/v3_style_guide.md), any issues or PRs are welcome in its new location. Thanks!
