### ISSUE TITLE
'Glue' missing for included resources

### ISSUE THREAD

**Issue by Gerg** [cloudfoundry/cc-api-v3-style-guide#35]
How do you tell which type of included resource goes with another resource (through a relationships object?

**Comment by Gerg** [comment]
``` json
{
  "guid": "xyz",
  "resource_field": "value",
  "relationships" : {
    "subresource": {"guid": "abc"},
    "other_resource": {"guid": "def"}
  },
  "included": {
    "subresources": [
      {
        "guid": "abc",
        "subresource_field": "other value",
        "relationships": {
           "other_resource": { "guid":  "ght" }
        }
      }
    ],
    "other_resources": [
      {
        "guid": "def",  
        "other_resource_field": "Zach",
      },
      {
        "guid": "ght",
        "other_resource_field": "Dances",
      },
    ]
  }
}
```

^ something like this

**Comment by Gerg** [comment]
Open question: Is the normalization worth it?

**Comment by dieucao** [comment]
https://www.pivotaltracker.com/story/show/103428852

**Comment by sweinstein22** [comment]
We are archiving this repo in favor of colocating the information [in the ccng repo](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/docs/v3_style_guide.md), any issues or PRs are welcome in its new location. Thanks!
