### ISSUE TITLE
Include fields using dot notation instead of square brackets.

### ISSUE THREAD

**Issue by Gerg** [cloudfoundry/cc-api-v3-style-guide#38]
`/v3/apps/:guid?fields[space]=guid,name&fields[organization]=guid,name`

Vs

`/v3/apps/:guid?fields=space.guid,space.name,organization.guid,organization.name` 

The second way seems slightly more consistent with the include syntax.

**Comment by dieucao** [comment]
Going with the current proposal for square brackets.  It follows the jsonapi recommendation which we have been sticking close to.
