### ISSUE TITLE
procesess example relationships clarification

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/cc-api-v3-style-guide#39]
There an example included in the doc:

```
PUT /v3/apps/:guid/processes/web/scale
```

Should that example be something like this:

```
PUT /v3/apps/:app_guid/relationships/processes/:process_guid/scale
PUT /v3/processes/:process_guid/scale
```

**Comment by cppforlife** [comment]
Additionally what is the reasoning behind adding /relationships/ part of the url? Imho it's less consistent with the query pattern `GET /v3/droplets?app_guids=:app_guid`.

**Comment by zrob** [comment]
the relationship subresource is only meant for managing relationships between resources, not for getting full resources.

so these to urls would live together, but return different things:

GET /v3/apps/:guid/relationships/processes
{
data: [{guid: process-guid }]
}

GET /v3/apps/:guid/processes
{
resources: [
{ guid: proc-guid, type: proc-type, .... all the process fields }
]
}

so modifying whethere there is a relationship between an app and its process would be at 
PATCH /v3/apps/:guid/relationships/processes

but modifying the actual process it self would be like
PATCH /v3/apps/:guid/processes/:proc_type

**Comment by dieucao** [comment]
Did this help clarify?

**Comment by dieucao** [comment]
Closing this issue. Feel free to re-open if we didn't address your concern.
