### ISSUE TITLE
patching relationships (data key)

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/cc-api-v3-style-guide#40]
Patching relationships uses `data` key. It feels inconsistent from other nouns: `resources`, `resource`.

**Comment by zrob** [comment]
we basically just copied from jsonapi to have a key to make the json valid.

it seems like a resource is a complete thing so i don't know if that make sense for something where we just pass guids, but something that felt better than data would be totally reasonable

**Comment by dieucao** [comment]
We can't come up with a better word, so we'll stick with data for now.
