### ISSUE TITLE
what is a resource key in error response

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/cc-api-v3-style-guide#44]
```
{
  "status": 400,
  "code": 123455,
  "type": "Invalid Request",
  "description": "The request body is not valid.",
  "errors": [
    {
      "resource": "app",
      "messages": [
        "Names must be unique",
        "Names may not contain numbers"
      ]
    },
    {
      "resource": "lunch",
      "messages": [
        "Potatoes cannot be perfectly round"
      ]
    }
  ]
}
```

In which scenario would above example response be returned, that is multiple resource are affected? And of different resource types?

**Comment by zrob** [comment]
hmm, we had been playing with the idea that a user would want to push an app through a single endpoint

aka
POST /the_whole_app
{
app { name }
routes [{ blue}, { green}]
bindings [{instance_sql}, {instance_message_queue}]
}

we haven't actually fleshed anything like that out nor have immediate plans to do so

**Comment by sweinstein22** [comment]
We are archiving this repo in favor of colocating the information [in the ccng repo](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/docs/v3_style_guide.md), any issues or PRs are welcome in its new location. Thanks!
