### ISSUE TITLE
Formal specs for CC API V3 enabling automated client generation

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cc-api-v3-style-guide#46]
+1 for a formal schema for the v3 api as to ease automatic client generations (api explorer, java sdk, go sdk...) (e.g. swagger format)  

Automated tests on the formal schema may also help checking the style guide is respected. 

https://www.pivotaltracker.com/story/show/99237980 seems to only consider documentation benefits so far and not yet client generation benefits (e.g. https://github.com/swagger-api/swagger-codegen https://github.com/swagger-api/swagger-codegen/issues/325 )

**Comment by dieucao** [comment]
@gberche-orange We're interested in making the api docs clearer and making the maintaining of those docs as simple as possible.  We had evaluated using swagger but we would prefer something more freeform.  It is not a current goal for the CAPI team to support automatic client generation.

**Comment by gberche-orange** [comment]
Thanks for your response @dieucao 

Can you share rationales for the non-goal in automatic client generation, w.r.t. the effort required to maintain clients in the different langages within the cf-community (js, go, java) ?

Is it that the CAPI team does not believe in automatically geneated clients, e.g. that the automatically generated client are not of sufficient quality or meeting the api users needs ? 

Is it rather a resource allocation issue (i.e. the effort that is spent in manually maintaining the clients in other teams can not be easily allocated to factor out this effort in the CAPI team) ?

**Comment by dieucao** [comment]
@gberche-orange I think it's some of amount of both.  I would rather focus the team's efforts on enabling functionality on the platform as opposed to working on expressing the cc api using the swagger or blueprint schemas.

**Comment by CAFxX** [comment]
Sorry for chiming it so late in the game but I agree with @gberche-orange that having a formal API definition would really help ease the pain of extending (and operating) the platform. It's not always practical to wrap the CLI at the heart of your operator/user automation. 

I think this would be a pretty effective way of encouraging the growth of the CF ecosystem.

**Comment by gberche-orange** [comment]
Maybe @hichristineyeh could reconsider as part of 2019 CAPI [UX survey](https://goo.gl/forms/A01pcE5Y7UFxsYNf2)

**Comment by siennathesane** [comment]
I think there's a lot of value here for the community, happy to assist where I can to make this a reality.

**Comment by pburkholder** [comment]
This would be an asset for satisfying auditors and pentesters. Hope you can make it happen!

**Comment by pburkholder** [comment]
TIL there's a long-dormant swagger project: https://github.com/cloudfoundry-incubator/cf-swagger

There's also cf-dev maillist discussion about formally closing it: https://lists.cloudfoundry.org/g/cf-dev/message/9277

**Comment by sweinstein22** [comment]
We are archiving this repo in favor of colocating the information [in the ccng repo](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/docs/v3_style_guide.md), any issues or PRs are welcome in its new location. Thanks!
