### ISSUE TITLE
Document gzip encoding support

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cc-api-v3-style-guide#47]
Would be nice to consider supporting gzip encoding for the json payload responses as to speed up responses over internet connections ('Accept-Encoding' header)

**Comment by dieucao** [comment]
This is something we think is reasonable to include support for in the CC API. Since this in an additive change, we could easily include this in a 3.x+ release.

**Comment by sweinstein22** [comment]
We are archiving this repo in favor of colocating the information [in the ccng repo](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/docs/v3_style_guide.md), any issues or PRs are welcome in its new location. Thanks!
