### ISSUE TITLE
Illustrate support for non ascii characters in query params

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cc-api-v3-style-guide#48]
Would be nice to clarify support for non ascii characters in query params, such as support for IRI https://en.wikipedia.org/wiki/Internationalized_resource_identifier as to avoid mojibake bugs such as the one presumed in https://github.com/cloudfoundry/cli/issues/560

**Comment by dieucao** [comment]
Updated with the link you suggested
Thanks @gberche-orange !
