### ISSUE TITLE
consider I18N of user-facing messages

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cc-api-v3-style-guide#49]
https://github.com/cloudfoundry/cc-api-v3-style-guide#proposal

Would useful to consider I18N of user-facing messages. 

Cf related thread for service broker error messages at http://cf-dev.70369.x6.nabble.com/cf-dev-Announcing-Experimental-support-for-Asynchronous-Service-Operations-tp287p1471.html May be the CC API could accept a "Accept-Language: zh_Hans" header and try to return localized messages when available in the accepted locale.

**Comment by sweinstein22** [comment]
We are archiving this repo in favor of colocating the information [in the ccng repo](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/docs/v3_style_guide.md), any issues or PRs are welcome in its new location. Thanks!
