### ISSUE TITLE
Give examples of collections that may wish to implement a custom pagination strategy

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/cc-api-v3-style-guide#5]
"This section will describe the preferred pagination strategy, however an individual collection may choose to implement a different strategy for performance reasons."

This sentence raises more questions than it answers. What are situations in which a different strategy is desired? Should we be documenting this before the situation has ever occurred?

**Comment by Gerg** [comment]
We will just delete the sentence.

**Comment by jeffpak** [comment]
Pew pew pew! :gun: Deleted. b1e2000
