### ISSUE TITLE
Suggestions from Data Vis team

### ISSUE THREAD

**Issue by stupakov** [cloudfoundry/cc-api-v3-style-guide#51]
- [Example for PUT](https://github.com/cloudfoundry/cc-api-v3-style-guide#examples-2) : text that reads "Update a resource" should be phrased "triggering an action" instead.
- For a PATCH, if a subset of the changes cannot be applied, do all changes get ignored/rolled back?  What code(s) come back when data is missing / invalid or the request tries to set a read-only or non-existent field?
- [Links](https://github.com/cloudfoundry/cc-api-v3-style-guide#links) - is it the case that actions always have a 'method' field, and resources do not specify a 'method'? If so, this could be mentioned explicitly.
- [Pagination](https://github.com/cloudfoundry/cc-api-v3-style-guide#links) - order_by: plus signs (+) in the query component of a URI should be encoded (%2B).
- [Filtering](https://github.com/cloudfoundry/cc-api-v3-style-guide#filtering) - Is there a difference between `/v3/apps?q=memory:512` and `/v3/apps?memory=512`, or is one preferred? If both ways of searching are to be kept, the documentation could mention the reason for the overlap and provide guidelines for how to use one method or the other, or if it's ok to mix them in the same request (e.g. `/v3/apps?names=the_name&q=memory:512`).
- [Relationships](https://github.com/cloudfoundry/cc-api-v3-style-guide#proposal-1) - The first example of a `POST` request shows a `links` section in the request body, which seems incorrect.

**Comment by TiraO** [comment]
On Filtering:  I agree that the q=name:value&q=name2>value2 thing is weird. It looks like q is only around so you can do comparison operators (>,<,IN). What if you did name=value&name2=>value2? Then you wouldn't need the q syntax at all.

**Comment by dieucao** [comment]
The q= syntax was erroneously added to the style guide.  We've removed it and reopened a separate issue to include an example of what to do with comparision operators.

**Comment by zrob** [comment]
Thanks for the feedback!

I think I've addressed all the issues with updates to the docs.

**Comment by dieucao** [comment]
Going to close this issue.  Please feel free to reopen or open a new issue if we didn't quite address all the things.
