### ISSUE TITLE
meaning of visibility

### ISSUE THREAD

**Issue by dkoper** [cloudfoundry/cc-api-v3-style-guide#53]
Can you clarify these scenarios? What is a user with no visibility? I completely lost you there.

First time I'm reading this, starting from the top, getting to:
https://github.com/cloudfoundry/cc-api-v3-style-guide#responses-collection

**Comment by sweinstein22** [comment]
We are archiving this repo in favor of colocating the information [in the ccng repo](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/docs/v3_style_guide.md), any issues or PRs are welcome in its new location. Thanks!
