### ISSUE TITLE
sort order for string fields

### ISSUE THREAD

**Issue by dkoper** [cloudfoundry/cc-api-v3-style-guide#54]
In https://github.com/cloudfoundry/cc-api-v3-style-guide#pagination

Can string fields be specified to order_by? (The examples all use date/time fields).

If so, how do you sort text?
Does 'Apple' come before 'after'? (ascii order)
Does 'Köper' come next to 'Koper' or does it come somewhere after 'Kzach'?
Basically, will 'order_by' on text fields only target ASCII or also target non-English locales?

In the CIMI spec (from 2.0.0) we define ordering as:
Ordering is based on a binary comparison of the transformed strings according to the rules of the Normalization Form KD of the Unicode standard as defined in Unicode Standard Annex (UAX), annex #15. Which basically means it orders as you would expect it should in any language.
Java actually has built-in classes to provide this sorting, I assume/hope golang has too.

I would not let this up to the implementer to decide.

**Comment by sweinstein22** [comment]
We are archiving this repo in favor of colocating the information [in the ccng repo](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/docs/v3_style_guide.md), any issues or PRs are welcome in its new location. Thanks!
