### ISSUE TITLE
when does updated_at gets updated?

### ISSUE THREAD

**Issue by dkoper** [cloudfoundry/cc-api-v3-style-guide#55]
https://github.com/cloudfoundry/cc-api-v3-style-guide#resources

Does updated_at get updated by any PUT or PATCH action on the resource?
E.g. when I do a PUT on my app to start it, and its state changes to 'STARTING' (and it has a field representing that), does updated_at get updated as well? Or only for updates to static fields like name?

What if the field in a resource displays its current state (not desired state) and crashed by itself, will the transitional states (STOPPED, STARTING, etc.) cause the updated_at field to be updated?

I can imagine I'd rather know when my app was started, stopped, etc. than when it was renamed last. But implementation-wise it may be more difficult for the backend to determine when the state changed if you rely on state polling.

**Comment by sweinstein22** [comment]
We are archiving this repo in favor of colocating the information [in the ccng repo](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/docs/v3_style_guide.md), any issues or PRs are welcome in its new location. Thanks!
