### ISSUE TITLE
dealing with unknown query parameters

### ISSUE THREAD

**Issue by dkoper** [cloudfoundry/cc-api-v3-style-guide#56]
https://github.com/cloudfoundry/cc-api-v3-style-guide#query-parameters

You have "If any request receives a query parameter it does not understand, the response MUST be a 400 Bad Request.".
We're run into a case where this was (would have been) annoying for the CLI. The CLI tries to stay compatible with old and new versions of the backend API. If a new query parameter is added to the API, e.g. one that makes the response more efficient but does not change it substantially (like sorting - if you hadn't supported that already, or filtering), we'd like to take advantage of it knowing and accepting that only CLI users with newer backends so their effect.
But if endpoints have to return an error for unknown (e.g. future) query parameters, we'd have to branch and only add the query parameter if the endpoint is of a certain version, which makes the client more complex.

I think it's common to ignore query parameters that are not understood. Client developers will notice if the param does not take effect and will check their spelling - no need for the server to point the typo out.

**Comment by sweinstein22** [comment]
We are archiving this repo in favor of colocating the information [in the ccng repo](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/docs/v3_style_guide.md), any issues or PRs are welcome in its new location. Thanks!
