### ISSUE TITLE
How does PATCHing work?

### ISSUE THREAD

**Issue by Gerg** [cloudfoundry/cc-api-v3-style-guide#57]
Related story: https://www.pivotaltracker.com/story/show/148425069

Currently we do not present a well-defined notion of what "partial update" means. For example. if you have a resource:

```
{
"foo": "bar",
"baz": {
    "qux": "corge",
    "grault": "waldo"
   }
}
```

if I PATCH
```
{
 "foo": "fred",
}
```

then I get 

```
{
"foo": "fred",
"baz": {
    "qux": "corge",
    "grault": "waldo"
   }
}
```

which is as expected.

However if I PATCH
```
{
"baz":  {
    "qux": "plugh",
  }
}
```

then it is unclear whether I will get 

```
{
"foo": "bar",
"baz": {
    "qux": "plugh",
    "grault": "waldo"
   }
}
```
or

```
{
"foo": "bar",
"baz": {
    "qux": "plugh"
   }
}
```
For reference, [this RFC](https://tools.ietf.org/html/rfc7396) says the first result is correct. There are instances in our API however, that behave like the second result (updating lifecycle on an app, for instance)

Also, looking at interpretations of the [original PATCH RFC](https://tools.ietf.org/html/rfc5789), it seems like the most-proper interpretation would be something like:

```
{ 
  "op": "add",
  "variable": "/baz/quix",
  "value": "plugh" 
}
```

It's too late to implement that though.

---
Other links:
- https://en.wikipedia.org/wiki/Patch_verb
- https://github.com/zalando/restful-api-guidelines/issues/124
- https://williamdurand.fr/2014/02/14/please-do-not-patch-like-an-idiot/

**Comment by sweinstein22** [comment]
We are archiving this repo in favor of colocating the information [in the ccng repo](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/docs/v3_style_guide.md), any issues or PRs are welcome in its new location. Thanks!
