### ISSUE TITLE
502 vs 503

### ISSUE THREAD

**Issue by Gerg** [cloudfoundry/cc-api-v3-style-guide#58]
The style guide currently distinguishes between 502 and 503. Since CC is not serving as a proxy, should we only return 503s?

**Comment by sweinstein22** [comment]
We are archiving this repo in favor of colocating the information [in the ccng repo](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/docs/v3_style_guide.md), any issues or PRs are welcome in its new location. Thanks!
