### ISSUE TITLE
Clarify support for bi-directional relationships (to reduce chatty interactions)

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cc-api-v3-style-guide#60]
The style guide and current api proposal seem to only illustrate relationships between resource A and B, but which are always accessed from A to B. 

In some cases, this makes the interactions quite chatty, see for instance [V3 service plan proposal](https://docs.google.com/document/d/1dwNbNy99f1qgKRfHy9hmc7B82XtcAtn0Wjg3KUpf7fo/edit#)

> The display of the CLI command “cf service-access” is very slow for admins, likely sign of a currently chatty API. On my CF lab deployment with 36 brokers, this takes 542 REST requests with many duplicated calls
> 
> CF_TRACE=true cf service-access | sort | uniq -c | sort -n -r
> 43 GET /v2/organizations/87505508-4c09-499e-933c-eb89582cb9a5 HTTP/1.1
> [...]
> 

It might make sense to make the relationship also accessible from B to A, at least for the read/list operations.

For example, as suggested into 
https://docs.google.com/document/d/1dwNbNy99f1qgKRfHy9hmc7B82XtcAtn0Wjg3KUpf7fo/edit?disco=AAAADgoM7og

> a read endpoint such as /v3/organizations/:org_guid/relationships/plans that would return all accessible service plans and visibilities for a given organization, avoiding currently chatty api calls that Cf CLI has to make.

**Comment by sweinstein22** [comment]
We are archiving this repo in favor of colocating the information [in the ccng repo](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/docs/v3_style_guide.md), any issues or PRs are welcome in its new location. Thanks!
