### ISSUE TITLE
Support for notifications of async job completion

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cc-api-v3-style-guide#61]
Currently, I understand that the job API require it to be polled to check its status. This makes asynchronous UX slow at best, and usually pushes the polling responsibility to end users.

Was it considered to have the the job API support a scaleable notification mechanism so that users that don't want to poll for underlying async operations, can enjoy a responsive blocking UX ?

See related CLI request at https://github.com/cloudfoundry/cli/issues/1354#issuecomment-427070213

(duplicated [comment from V3 Asynchronous Operations Proposal](https://docs.google.com/document/d/1CWmumhtyY0EAatDmg0zNkSSfpMDAHKfAIpoQI6whaC4/edit?disco=AAAAEELYKMs) )

**Comment by sweinstein22** [comment]
We are archiving this repo in favor of colocating the information [in the ccng repo](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/docs/v3_style_guide.md), any issues or PRs are welcome in its new location. Thanks!
