### ISSUE TITLE
"Fields" query params should be normal arrays

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/cc-api-v3-style-guide#8]
When requesting partial resources, I expect to provide the normal array syntax. For example, `GET /resource?fields=guid,name` should be `GET /resource?fields[]=guid&fields[]=name`.

Otherwise, CC consumers will have to write code to serialize arrays in two different ways, depending on which array is being serialized.

**Comment by Gerg** [comment]
Duplicate of #12
