### ISSUE TITLE
Examples with non-real types are confusing

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/cc-api-v3-style-guide#9]
I'd prefer to see examples with `/v3/apps` instead of `/v3/resources`. It makes things much easier to understand, especially when nested resources are part of the example.

**Comment by Gerg** [comment]
Via cage match 1: The team has decided to use concrete examples throughout the document. Instead of things like resource.sub_resource, we should talk about things like space.app.

**Comment by jeffpak** [comment]
Actionated. f6c76e7

:tada:
